-- ROLES
CREATE ROLE dba;
CREATE ROLE metge;
CREATE ROLE infermeria;
CREATE ROLE administracio;
CREATE ROLE recepcio;
CREATE ROLE rrhh_direccio;
CREATE ROLE analista_bi;

-- PERSONAL
GRANT ALL ON PERSONAL TO dba;
GRANT SELECT ON PERSONAL TO metge, infermeria, administracio, analista_bi;
GRANT SELECT, INSERT, UPDATE ON PERSONAL TO recepcio, rrhh_direccio;

-- PERSONAL_MEDIC
GRANT ALL ON PERSONAL_MEDIC TO dba;
GRANT SELECT ON PERSONAL_MEDIC TO metge;
GRANT SELECT, INSERT, UPDATE ON PERSONAL_MEDIC TO rrhh_direccio;

-- PERSONAL_VARI
GRANT ALL ON PERSONAL_VARI TO dba;
GRANT SELECT, INSERT, UPDATE ON PERSONAL_VARI TO rrhh_direccio;

-- INFERMERIA
GRANT ALL ON INFERMERIA TO dba;
GRANT SELECT ON INFERMERIA TO metge, infermeria;
GRANT SELECT, INSERT, UPDATE ON INFERMERIA TO rrhh_direccio;

-- PLANTES
GRANT ALL ON PLANTES TO dba;
GRANT SELECT ON PLANTES TO metge, infermeria, administracio, recepcio, rrhh_direccio;

-- HABITACIONS
GRANT ALL ON HABITACIONS TO dba;
GRANT SELECT ON HABITACIONS TO metge, infermeria, recepcio, rrhh_direccio;
GRANT SELECT, INSERT, UPDATE ON HABITACIONS TO administracio;

-- QUIROFANS
GRANT ALL ON QUIROFANS TO dba;
GRANT SELECT ON QUIROFANS TO metge, infermeria, administracio, recepcio, rrhh_direccio;

-- APARELLS_MEDICS
GRANT ALL ON APARELLS_MEDICS TO dba;
GRANT SELECT ON APARELLS_MEDICS TO metge, infermeria, analista_bi;

-- PACIENT
GRANT ALL ON PACIENT TO dba;
GRANT SELECT, INSERT, UPDATE ON PACIENT TO metge, administracio;
GRANT SELECT ON PACIENT TO infermeria, rrhh_direccio, analista_bi;

-- VISITA
GRANT ALL ON VISITA TO dba;
GRANT SELECT, INSERT, UPDATE ON VISITA TO metge, infermeria;
GRANT SELECT, INSERT ON VISITA TO administracio;
GRANT SELECT ON VISITA TO analista_bi;

-- MEDICAMENT
GRANT ALL ON MEDICAMENT TO dba;
GRANT SELECT ON MEDICAMENT TO metge, infermeria, analista_bi;

-- RECEPTA_VISITA
GRANT ALL ON RECEPTA_VISITA TO dba;
GRANT SELECT, INSERT, UPDATE ON RECEPTA_VISITA TO metge;
GRANT SELECT ON RECEPTA_VISITA TO infermeria, analista_bi;

-- RESERVA_HABITACIO
GRANT ALL ON RESERVA_HABITACIO TO dba;
GRANT SELECT ON RESERVA_HABITACIO TO metge, infermeria;
GRANT SELECT, INSERT, UPDATE ON RESERVA_HABITACIO TO administracio;
GRANT SELECT ON RESERVA_HABITACIO TO analista_bi;

-- RESERVA_QUIROFAN
GRANT ALL ON RESERVA_QUIROFAN TO dba;
GRANT SELECT, INSERT, UPDATE ON RESERVA_QUIROFAN TO metge, administracio;
GRANT SELECT ON RESERVA_QUIROFAN TO infermeria, analista_bi;

-- PERSONAL_OPERACIO
GRANT ALL ON PERSONAL_OPERACIO TO dba;
GRANT SELECT, INSERT, UPDATE ON PERSONAL_OPERACIO TO metge, infermeria;
GRANT SELECT ON PERSONAL_OPERACIO TO analista_bi;
